-- Supabase SQL Editor에서 실행한 뒤 앱을 배포하세요.

create table if not exists public.budget_items (
  item text primary key,
  budget_amount bigint not null default 0,
  spent_amount bigint not null default 0,
  fine_amount bigint not null default 0
);

create table if not exists public.expense_requests (
  id bigint generated by default as identity primary key,
  request_date text not null,
  dept_name text not null,
  item_name text not null,
  amount bigint not null,
  status text not null default '대기'
);

create index if not exists expense_requests_status_idx
  on public.expense_requests (status);

alter table public.budget_items enable row level security;
alter table public.expense_requests enable row level security;

-- Streamlit 서버에서만 service_role 키를 쓰면 RLS는 우회됩니다.
-- anon 키만 쓸 경우 아래 정책을 필요에 맞게 조정하세요.
